### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Peilonrayz** [Peilonrayz/mam#1]
Core:

 - [ ] Change from Nox to Invoke
    - [ ] Add support for NPM.
        - [ ] Add pyright support.
    - [ ] Add parallel execution.
 - [ ] Update `_mam.yaml` layout.
 - [ ] Improve configs `_mutations` globbing.
 - [ ] Add a new base file to make extending different common environments easier.
    - [ ] PIP-{glob/dir}
    - [ ] NPM - {glob/dir}
 - [ ] Ensure everything is fully typed.
 - [ ] Add tests.
 - [ ] Add documentation.

Extras:

 - [ ] Ensure correct config argument is set for each task.
 - [ ] Ensure correct excludes argument is set for each task.
 - [ ] Update `@mam.config:mutations.defer` to support all types.
